language: java
service: docker


before_install:
  - docker version
  - docker info

cache:
  directories:
    - ~/.m2/repository

notifications:
  email:
    - ro.franchini@gmail.com

script:
  ./mvnw deploy --settings .travis/settings.xml

jdk:
  - openjdk8
