language: java
service: docker


before_install:
  - docker version
  - docker info
  - cd ./src/main/docker/orientdb && ./build.sh && cd -
  - cd ./src/main/docker/postgresql-dvdrental && ./build.sh && cd -

cache:
  directories:
    - ~/.m2/repository

notifications:
  email:
    - ro.franchini@gmail.com

script:
  ./mvnw deploy --settings .travis/settings.xml

jdk:
  - openjdk8
