language: java
service: docker


before_install:
  - docker version
  - docker info


cache:
  directories:
    - ~/.m2/repository

notifications:
  email:
    - arcade@arcadeanalytics.com

script: ./mvnw -fae deploy --settings .travis/settings.xml

jdk:
  - openjdk8

after_success:
  - bash <(curl -s https://codecov.io/bash) -t ${env.CODECOV_TOKEN}